#!/bin/bash

# script for creating builtin modules file

MODULES_DIR=/lib/modules/$(uname -r)
mkdir -p ${MODULES_DIR}

# touch ${MODULES_DIR}/modules.{builtin,order}

/bin/truncate --size=0 ${MODULES_DIR}/modules.builtin
/bin/truncate --size=0 ${MODULES_DIR}/modules.order

for i in /sys/module/*; do echo kernel/${i##**/}.ko; done >> ${MODULES_DIR}/modules.builtin

depmod -a
